# gen_hardware_matrix.awk -- render the hardware verification matrix.
#
#   awk -f tools/gen_hardware_matrix.awk tests/results/*.tsv HARDWARE_TESTING.md
#
# Reads the result files written by the HIL suite (tests/results/*.tsv), then
# copies HARDWARE_TESTING.md to stdout with the generated block replaced. Only
# the region between the BEGIN/END markers is touched; every other line,
# including all the hand-written prose, passes through untouched.
#
# Result files are the record of what ran on what; this table is only a view of
# them. Output is plain GitHub-flavoured markdown -- no HTML, no line breaks
# inside cells -- so it renders the same in Doxygen, pandoc and MkDocs.
#
# Row order follows the order the result files are given, which the shell glob
# sorts, so the output is deterministic.

BEGIN {
    FS = "\t"
    begin_marker = "<!-- BEGIN GENERATED MATRIX -->"
    end_marker = "<!-- END GENERATED MATRIX -->"
    file_count = 0
    in_generated_block = 0
}

# --- Collect one result file ----------------------------------------------

FILENAME ~ /\.tsv$/ {
    if (FILENAME != current_file) {
        current_file = FILENAME
        files[++file_count] = FILENAME
    }

    if ($1 == "M") {
        meta[FILENAME, $2] = $3
    } else if ($1 == "T") {
        n = ++test_count[FILENAME]
        test_name[FILENAME, n] = $2
        test_outcome[FILENAME, n] = $3
        test_summary[FILENAME, n] = $4
        test_detail[FILENAME, n] = $5
        tally[FILENAME, $3]++
    }
    next
}

# --- Rewrite the document --------------------------------------------------

$0 ~ begin_marker {
    print
    emit_matrix()
    in_generated_block = 1
    next
}

$0 ~ end_marker {
    in_generated_block = 0
    print
    next
}

{ if (!in_generated_block) print }

# --- Rendering -------------------------------------------------------------

function cell(text) {
    if (text == "")
        return "--"
    gsub(/\|/, "\\|", text)   # a pipe in free text would split the row
    return text
}

function outcome_label(outcome) {
    if (outcome == "pass")        return "accepted"
    if (outcome == "fail")        return "**FAILED**"
    if (outcome == "unsupported") return "unsupported (refusal verified)"
    if (outcome == "discrepancy") return "discrepancy (pinned)"
    if (outcome == "skip-build")  return "skipped (firmware build)"
    if (outcome == "skip-level")  return "skipped (run level)"
    return outcome
}

function coverage_summary(f,   parts, n) {
    parts = ""
    n = tally[f, "pass"] + 0;        if (n) parts = n " accepted"
    n = tally[f, "discrepancy"] + 0; if (n) parts = parts (parts ? ", " : "") n " discrepancy"
    n = tally[f, "unsupported"] + 0; if (n) parts = parts (parts ? ", " : "") n " unsupported (verified)"
    n = tally[f, "skip-build"] + 0;  if (n) parts = parts (parts ? ", " : "") n " skipped (build)"
    n = tally[f, "skip-level"] + 0;  if (n) parts = parts (parts ? ", " : "") n " skipped (level)"
    n = tally[f, "fail"] + 0;        if (n) parts = parts (parts ? ", " : "") "**" n " FAILED**"
    return parts == "" ? "no results" : parts
}

function emit_matrix(   i, f, j) {
    print ""
    print "<!-- Generated by tools/gen_hardware_matrix.awk from tests/results/*.tsv."
    print "     Do not edit this block by hand; run `make hardware-matrix`. -->"
    print ""

    if (file_count == 0) {
        print "_No hardware runs recorded yet. Run `make test-hardware` against a"
        print "receiver to add one._"
        print ""
        return
    }

    print "| Model | Board / integrator | Firmware | Interface | Coverage | Contributor | Date |"
    print "| --- | --- | --- | --- | --- | --- | --- |"

    for (i = 1; i <= file_count; i++) {
        f = files[i]
        printf "| %s | %s | %s | %s @ %s | %s | %s | %s |\n",
            cell(meta[f, "model"]),
            cell(meta[f, "board"]),
            cell(meta[f, "firmware"]),
            cell(meta[f, "interface"]),
            cell(meta[f, "baud"]),
            coverage_summary(f),
            cell(meta[f, "contributor"]),
            cell(meta[f, "date"])
    }

    print ""
    print "### Per-device detail"
    print ""

    for (i = 1; i <= file_count; i++) {
        f = files[i]
        printf "**%s -- %s (%s)**, run at level `%s`\n\n",
            cell(meta[f, "model"]), cell(meta[f, "board"]),
            cell(meta[f, "firmware"]), cell(meta[f, "level"])
        print "| Command | Result | Notes |"
        print "| --- | --- | --- |"
        for (j = 1; j <= test_count[f]; j++) {
            printf "| %s | %s | %s |\n",
                cell(test_summary[f, j]),
                outcome_label(test_outcome[f, j]),
                cell(test_detail[f, j])
        }
        print ""
    }
}
